### ISSUE TITLE
Issue in loading

### ISSUE THREAD

**Issue by Fbahashwan** [JulianoMuteki/StudyProject#4]
the type or namespace name 'IProductApplicationService' could not be found (are you missing a using directive or an assembly reference?)	StudyProject.Application

**Comment by JulianoMuteki** [comment]
Can you try again?

**Comment by Fbahashwan** [comment]
The problem is still!

**Comment by Fbahashwan** [comment]
![image](https://user-images.githubusercontent.com/22313076/55356218-f0b88280-54d2-11e9-881f-a1fcad3b04b2.png)

**Comment by JulianoMuteki** [comment]
Could you try to do clone again?
